backend:
  name: git-gateway
  branch: master

media_folder: "images/uploads"

collections:
  - name: pages
    label: Pages
    label_singular: 'Post'
    folder: content
    fields:
      - label: "Layout"
        name: "layout" 
        widget: "hidden"
        default: "single"
      - label: "Type"
        name: "type"
        widget: "hidden"
        default: "_default"
      - label: Title
        name: title
        widget: string
      - label: Publish Date
        name: date
        widget: datetime
      - label: Body
        name: body
        widget: markdown
